-- Yuri Code AI — PostgreSQL baseline schema
-- Apply this migration to the production database before enabling persistence.

create table if not exists projects (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  created_at timestamp without time zone default now()
);

create index if not exists ix_projects_id on projects (id);

create table if not exists conversations (
  id integer generated by default as identity primary key,
  external_id varchar(255) not null unique,
  title varchar(255),
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create index if not exists ix_conversations_id on conversations (id);
create index if not exists ix_conversations_external_id on conversations (external_id);

create table if not exists messages (
  id integer generated by default as identity primary key,
  role varchar(50) not null,
  content text not null,
  conversation_id integer not null,
  created_at timestamp without time zone default now()
);

create index if not exists ix_messages_id on messages (id);
create index if not exists ix_messages_conversation_id on messages (conversation_id);

create table if not exists memories (
  id integer generated by default as identity primary key,
  scope varchar(100) not null,
  key varchar(255) not null,
  value text
);

create index if not exists ix_memories_id on memories (id);

create table if not exists research_records (
  id integer generated by default as identity primary key,
  query text not null,
  url text,
  content text,
  created_at timestamp without time zone default now()
);

create index if not exists ix_research_records_id on research_records (id);
